### ISSUE TITLE
user-select : Hide myself when search

### ISSUE THREAD

**Issue by bmoriniere** [LuccaSA/lucca-front#1447]
In the user-select picker, "me" is always displayed as the top value. I understand it is useful and consistent to keep it by default, but when you start to search for someone, and your name does not match the search clue, it does not make sense to keep it in the options.

**Comment by lucienbertin** [comment]
i think i know the cause, it kinda worked 1-2 years ago but it was due to a bug in the implemantation of the possible overriding via DI of the user-service used.

user-searcher and me-first components both need a user-service, and this user-service needs to be overridable. 2 years ago they shared the same service because they both used the one that was provided at the user-select component level, so when you searched and me wasn't a possible result, the me option would hide

this implementation, though, didnt go well with overriding the service. when you tried to override the service used by the user-select and its subcomponents, it overrode the service used by the user-select, but not the one used by the user-searcher or me-first

with component tree looking like that
```
- your-component
  - user-select
    - user-searcher
    - me-first
```

LF component DI looks something like that

```ts
@Component({
  providers: [
    { provide: UserService, useClass: LfUserService },
  ],
}) class UserSelect {
  _service: IUserService
  constructor(
    @Inject(UserService) @skipSelf() hostService,
    @Inject(UserService) selfService
  ){
    this._service = hostService ?? selfService;
  }
```

> almost all LF componetns that depend on DI look like that
> this was made so the component is plug and play in 2017-2018 if my memory is correct, but in hindsight that was a bad idea

so you see, if you provide a user service at `your-component` level, it'll appear as host service for the `user-select` and it will use it instead of its fallback default LfUserService, thats good.

but, because the user-selects provides its own fallback, it becomes the hostService for its subcomponents, and thats bad, bordering on broken

the _quote good side effect quote_ was that user-searcher and me-first shared the same user-service instance, provided by user-select, and as a result when you searched in the user-searcher it impacted the results in me-first without needing the 2 to communicate.

to fix the DI bug, the user-select do not provide or get injected or consumme any user-service, it just passes the filters/orderBy/... to its children that may need it
see [here](https://github.com/LuccaSA/lucca-front/blob/master/packages/ng/user/src/lib/select/input/user-select-input.component.html#L16) and [there](https://github.com/LuccaSA/lucca-front/blob/master/packages/ng/user/src/lib/select/input/user-select-input.component.ts#L58)

but the result is that me-first and searcher do not share the same service instance anymore, and there is today no official way for themn to communicate

i think the best solution is for the seacher to expose its current search query as an output, so the user-select can pass it to the me-first component

exposing said search query could also be used to make work a kind of highlight in the results, showing what matched as a feedback for the end user. thats not the subject of this issue, but i wanted to write it to show that it might be a solution to several problems

peace
