### ISSUE TITLE
[UserPicture] Use initials in case of pictureHref error

### ISSUE THREAD

**Issue by 3htomit** [LuccaSA/lucca-front#2344]
Currently, in case the user picture href return an error we display an empty grey circle. Instead, it would be better to display the initials, as when there is no href.

**Comment by Supamiu** [comment]
To add on this:
We investigated a bit and it turns out the image href is loaded in a `style` entry that's using `background` to load the image, making it impossible to have alt or control over if the image failed or not.

A solution would be to make it use an `img` tag instead, using initials as alt text, but that would probably require some CSS tweaks.
