### ISSUE TITLE
select - selectionwith enter broken

### ISSUE THREAD

**Issue by afalaiselucca** [LuccaSA/lucca-front#705]
https://master-branch-lucca-front-luccasa.surge.sh/ng/#/refactor-select

**Comment by lucienbertin** [comment]
due to the fact that the select-input opens on `enter` and stops propagation - [see code](https://github.com/LuccaSA/lucca-front/blob/master/packages/ng/libraries/core/src/lib/select/input/select-input.component.ts#L109)

and when a basic option picker is opened, the select-input stays focuesd, so the `keydown.enter` event is stopped.

but when you open an advanced option picker with a searcher, the focus is passed to the search input, so the `keydown.enter` is caught by the overlay
