### ISSUE TITLE
[lu-option] L'utilisation de directives sur les lu-option ne fonctionne plus

### ISSUE THREAD

**Issue by bmoriniere** [LuccaSA/lucca-front#731]
L'utilisation de directives sur les `lu-option` ne fonctionne plus.

Observé avec le `translate` de ngx-translate : 
`<lu-option [value]="machin" translate="TRAD_KEY"></lu-option>` doit être remplacé par `<lu-option [value]="machin">{{'TRAD_KEY' | translate}}</lu-option>`

Observé aussi avec un `*ngIf` sur un `lu-select-clearer`, que j'ai du remplacer par un `[hidden]`

**Comment by lucienbertin** [comment]
the case for the clearer, i'm not surprised, its due to ng 8 adding a `static: true/false` to decorator `@ViewChild` and `@CiontentChild`, when i migratred, i set everything to `static: true`.

for the directive on lu-option i have no idea why it doesn't work anymore, have you tried with `[translate]="'TRAD_KEY'"` to force the binding ? it may be that the `ng-content` doesnt work like it did in ng7

**Comment by bmoriniere** [comment]
Actually, I made a mistake, `[hidden]` does not work either on the clearer, I had to set a class on some parent element to hide it with css 😕 
```
:not(.mod-nullable) ::ng-deep lu-select-clearer {
	display: none!important;
}
```
